### ISSUE TITLE
hpHosts.partial file has a trailing '.' on several dns names leading to duplicates

### ISSUE THREAD

**Issue by proxenus** [FadeMind/hosts.extended#1]
I've confirmed its that way coming from hphosts

an example with the domain 'www.virus-crash-ac2y7.info'

[root@localhost.extended]# grep www.virus-crash-ac2y7.info * -R
data/hpHosts.partial/hosts:127.0.0.1    www.virus-crash-ac2y7.info.
data/hpHosts/hosts:127.0.0.1    www.virus-crash-ac2y7.info
hosts:0.0.0.0 www.virus-crash-ac2y7.info.
hosts:0.0.0.0 www.virus-crash-ac2y7.info

the hosts file doesn't seem to care if both entries are there, but I've written a script to translate hosts into a zonefile for dns, and named takes it VERY personally :)

I know this will require a tweak in the removeDupsAndExcl function but I'm not python savvy enough to know what needs to be corrected.

**Comment by FadeMind** [comment]
@proxenus  report this issue directly here: https://github.com/StevenBlack/hosts/issues
Thanks. CC @StevenBlack

**Comment by proxenus** [comment]
My mistake. I had posted it here since I didn't think steve supported hphosts. I'll follow up with him.

**Comment by FadeMind** [comment]
@proxenus hpHosts files are not included in MAIN hosts project, but can be added. Maybe this bug affect other sources, so please report this upstream. Thanks.

**Comment by proxenus** [comment]
done! Thanks. https://github.com/StevenBlack/hosts/issues/271
